// Cross-tree non-CF byte-identity proof. Runs the plastic-only export case from
// each build in its OWN working directory (the test writes fs_export_plastic.gcode
// to cwd), twice per tree, normalises the single exporter timestamp line, and
// compares sha256. Pristine control = ctrl1220/buildctrl at 12205f3623.
const fs=require('fs');
const cp=require('child_process');
const c=require('crypto');
const ROOT='/mnt/c/Users/3ricj/.openvibely/repos/288e09695603e28b9fc187875ade9fdf';
const TREES={
  base: ROOT+'/ctrl1220/buildctrl/tests/libslic3r/Release',
  mod:  ROOT+'/buildfs/tests/libslic3r/Release'
};
const TMP='/tmp/fsbi';
const NORM=/^;\s*generated by .* at .*$/i;
function run(tree,tag){
  const dir=TMP+'/'+tree+'_'+tag;
  try{fs.unlinkSync(dir+String.fromCharCode(34)+/fs_export_plastic.gcode");}catch(e){}
  fs.mkdirSync(dir,{recursive:true});
  const exe=TREES[tree]+'/libslic3r_tests.exe';
  const r=cp.spawnSync(exe,['[FiberExport]','-c','Plastic-only export is deterministic and reaches the exporter'],
      {cwd:dir,encoding:'latin1',timeout:120000});
  const f=dir+'/fs_export_plastic.gcode';
  if(!fs.existsSync(f)){console.log('NO OUTPUT '+tree+' '+tag);console.log(r.stdout&&r.stdout.slice(-500));process.exit(1);}
  const raw=fs.readFileSync(f,'latin1');
  const lines=raw.split(/\r?\n/);
  let norm=0;
  const out=lines.map(l=>{ if(NORM.test(l)){norm++;return ';GENERATED-NORMALISED';} return l; }).join('\n');
  const buf=Buffer.from(out,'latin1');
  const sha=c.createHash('sha256').update(buf).digest('hex');
  const fans=lines.filter(l=>/^M106/.test(l)).length;
  return {bytes:raw.length,sha:sha,norm:norm,fan:fans};
}
fs.mkdirSync(TMP,{recursive:true});
const res={};
for(const t of ['base','mod']) for(const g of ['1','2']) res[t+g]=run(t,g);
for(const k of ['base1','base2','mod1','mod2'])
  console.log(k.padEnd(6)+' bytes='+String(res[k].bytes).padStart(7)+'  fan='+String(res[k].fan).padStart(3)+'  norm='+res[k].norm+'  sha='+res[k].sha);
const eq=(a,b)=>res[a].sha===res[b].sha && res[a].bytes===res[b].bytes;
console.log('');
console.log('pristine run1 vs run2 (self-determinism): '+(eq('base1','base2')?'BYTE-IDENTICAL':'DIFFER'));
console.log('modified run1 vs run2 (self-determinism): '+(eq('mod1','mod2')?'BYTE-IDENTICAL':'DIFFER'));
console.log('PRISTINE vs MODIFIED (r1 vs r1)        : '+(eq('base1','mod1')?'BYTE-IDENTICAL':'DIFFER'));
console.log('PRISTINE vs MODIFIED (r2 vs r2)        : '+(eq('base2','mod2')?'BYTE-IDENTICAL':'DIFFER'));
console.log('fan lines inside compared bytes: base='+res.base1.fan+' mod='+res.mod1.fan);
console.log('');
console.log(eq('base1','mod1')&&eq('base2','mod2')&&eq('base1','base2')&&eq('mod1','mod2')
  ? 'VERDICT: NON-CF OUTPUT BYTE-IDENTICAL (measured, cross-tree, cooling lines present)'
  : 'VERDICT: NOT BYTE-IDENTICAL');
