// Cross-tree non-CF byte-identity proof. Runs the plastic-only export case from
// each build in its OWN fresh working directory (the test writes
// fs_export_plastic.gcode to cwd), twice per tree, normalises the single exporter
// timestamp line, and compares sha256. Pristine control = ctrl1220/buildctrl at
// 12205f3623, built from unmodified source.
const fs = require('fs');
const cp = require('child_process');
const c  = require('crypto');

const ROOT = '/mnt/c/Users/3ricj/.openvibely/repos/288e09695603e28b9fc187875ade9fdf';
const EXE = {
  base: ROOT + '/ctrl1220/buildctrl/tests/libslic3r/Release/libslic3r_tests.exe',
  mod:  ROOT + '/buildfs/tests/libslic3r/Release/libslic3r_tests.exe'
};
const TMP = '/tmp/fsbi2';
const NORM = /^;\s*generated by .* at .*$/i;
const CASE = 'Plastic-only export is deterministic and reaches the exporter';

function run(tree, tag) {
  const dir = TMP + '/' + tree + '_' + tag + '_' + Date.now() + '_' + Math.floor(Math.random() * 1e6);
  fs.mkdirSync(dir, { recursive: true });
  cp.spawnSync(EXE[tree], ['[FiberExport]', '-c', CASE], { cwd: dir, encoding: 'latin1', timeout: 180000 });
  const f = dir + '/fs_export_plastic.gcode';
  if (!fs.existsSync(f)) { console.log('NO OUTPUT for ' + tree + ' ' + tag); process.exit(1); }
  const raw   = fs.readFileSync(f, 'latin1');
  const lines = raw.split(/\r?\n/);
  let norm = 0;
  const out = lines.map(function (l) {
    if (NORM.test(l)) { norm++; return ';GENERATED-NORMALISED'; }
    return l;
  }).join('\n');
  return {
    bytes: raw.length,
    sha:   c.createHash('sha256').update(Buffer.from(out, 'latin1')).digest('hex'),
    norm:  norm,
    fan:   lines.filter(function (l) { return /^M106/.test(l); }).length
  };
}

fs.mkdirSync(TMP, { recursive: true });
const res = {};
['base', 'mod'].forEach(function (t) { ['1', '2'].forEach(function (g) { res[t + g] = run(t, g); }); });

['base1', 'base2', 'mod1', 'mod2'].forEach(function (k) {
  console.log(k.padEnd(6) + ' bytes=' + String(res[k].bytes).padStart(7) +
    '  fan=' + String(res[k].fan).padStart(3) + '  norm=' + res[k].norm + '  sha=' + res[k].sha);
});

const eq = function (a, b) { return res[a].sha === res[b].sha && res[a].bytes === res[b].bytes; };
console.log('');
console.log('pristine run1 vs run2 (self-determinism): ' + (eq('base1', 'base2') ? 'BYTE-IDENTICAL' : 'DIFFER'));
console.log('modified run1 vs run2 (self-determinism): ' + (eq('mod1', 'mod2') ? 'BYTE-IDENTICAL' : 'DIFFER'));
console.log('PRISTINE vs MODIFIED (run1 vs run1)     : ' + (eq('base1', 'mod1') ? 'BYTE-IDENTICAL' : 'DIFFER'));
console.log('PRISTINE vs MODIFIED (run2 vs run2)     : ' + (eq('base2', 'mod2') ? 'BYTE-IDENTICAL' : 'DIFFER'));
console.log('fan lines inside the compared bytes: base=' + res.base1.fan + '  mod=' + res.mod1.fan);
console.log('');
const all = eq('base1', 'base2') && eq('mod1', 'mod2') && eq('base1', 'mod1') && eq('base2', 'mod2');
console.log(all ? 'VERDICT: NON-CF OUTPUT BYTE-IDENTICAL (measured, cross-tree, cooling lines present)'
                : 'VERDICT: NOT BYTE-IDENTICAL');
