// Measured non-CF byte-identity proof, cross-tree.
//
// Runs the plastic-only export case in N separate processes against EACH of two
// builds: the pristine base (ctrl1220/buildctrl) and the modified tree
// (buildfs). Both exes were built from a tree whose test source and preset
// files are byte-identical (verified by sha256 before this script runs), so the
// only thing that can differ between the two groups is exporter behaviour.
//
// Normalisation: exactly one line, the exporter's own generation timestamp.
// Nothing else is touched.
const fs = require('fs');
const cp = require('child_process');

const CASE = 'Plastic-only export is deterministic and reaches the exporter';
const TS = /^; generated by .* on .* at .*$/;
const N = 3;
const ROOT = '/mnt/c/Users/3ricj/.openvibely/repos/288e09695603e28b9fc187875ade9fdf';
const TMP = '/mnt/c/Users/3ricj/.openvibely/repos/b286adc9ffdb76b2fe4314806b97ad0a/.worktrees/task_d71213a54c246e952b54f607dae12df4/tmp';

const BUILDS = [
  { tag: 'base', exe: ROOT + '/ctrl1220/buildctrl/tests/libslic3r/Release/libslic3r_tests.exe' },
  { tag: 'mod',  exe: ROOT + '/buildfs/tests/libslic3r/Release/libslic3r_tests.exe' },
];

function run_and_norm(exe, tag, i) {
  cp.execSync('"' + exe + '" "' + CASE + '"', { cwd: require('path').dirname(exe), stdio: 'pipe', maxBuffer: 128 * 1024 * 1024 });
  const src = require('path').dirname(exe) + '/fs_export_plastic.gcode';
  const raw = fs.readFileSync(src, 'latin1');
  const L = raw.split('\n');
  let ts = 0;
  for (let k = 0; k < L.length; k++)
    if (TS.test(L[k].replace(/\r$/, ''))) { L[k] = '; TIMESTAMP_NORMALIZED'; ts++; }
  const np = TMP + '/x_' + tag + '_' + i + '.norm';
  fs.writeFileSync(np, L.join('\n'), 'latin1');
  const sha = cp.execSync('sha256sum ' + np, { encoding: 'latin1' }).split(' ')[0].trim();
  // fan lines, so the cooling path is shown to be inside the compared bytes
  const fan = raw.split('\n').filter(l => /^M10[67]\b/.test(l));
  return { sha, bytes: raw.length, ts, fan: fan.length };
}

const res = {};
for (const b of BUILDS) {
  res[b.tag] = [];
  for (let i = 0; i < N; i++) {
    const r = run_and_norm(b.exe, b.tag, i);
    res[b.tag].push(r);
    console.log(b.tag + ' run ' + (i + 1) + ': raw_bytes=' + r.bytes + '  timestamp_lines=' + r.ts + '  fan_lines=' + r.fan + '  sha256=' + r.sha);
  }
}
console.log('');
for (const b of BUILDS) {
  const same = res[b.tag].every(r => r.sha === res[b.tag][0].sha);
  console.log(b.tag + ' self-determinism across ' + N + ' processes : ' + (same ? 'IDENTICAL' : 'DIFFER'));
}
const base = res.base[0].sha, mod = res.mod[0].sha;
console.log('');
console.log('PRISTINE BASE  vs MODIFIED  : ' + (base === mod ? 'BYTE-IDENTICAL' : 'DIFFER'));
console.log('  base ' + base);
console.log('  mod  ' + mod);
console.log('fan lines inside compared bytes : base=' + res.base[0].fan + ' mod=' + res.mod[0].fan +
            (res.base[0].fan > 0 ? '  (cooling path IS exercised by this comparison)' : '  (WARNING: no fan output)'));
