// Measured non-CF byte-identity proof, hardened.
//
// Runs the plastic-only export case N times in N SEPARATE processes (so the
// process-global object-id counter starts identically each time), normalises the
// single non-deterministic line the exporter writes (its own generation
// timestamp), and byte-compares. Also reports the object id so the counter
// artifact is visible rather than hidden.
const fs = require('fs');
const cp = require('child_process');

const EXE = process.argv[2];
const CASE = 'Plastic-only export is deterministic and reaches the exporter';
const PRISTINE = '303207d7ed6d8578c93a46dbe7444e688e503c9f725950512c506ea69d79d0e4';
const TS = /^; generated by .* on .* at .*$/;
const N = 3;

const outdir = '/mnt/c/Users/3ricj/.openvibely/repos/288e09695603e28b9fc187875ade9fdf/buildfs/tests/libslic3r/Release';
const tmp = '/mnt/c/Users/3ricj/.openvibely/repos/b286adc9ffdb76b2fe4314806b97ad0a/.worktrees/task_d71213a54c246e952b54f607dae12df4/tmp';

const res = [];
for (let i = 0; i < N; i++) {
  cp.execSync('"' + EXE + '" "' + CASE + '"', { cwd: outdir, stdio: 'pipe', maxBuffer: 64 * 1024 * 1024 });
  const raw = fs.readFileSync(outdir + '/fs_export_plastic.gcode', 'latin1');
  const L = raw.split('\n');
  let ts = 0;
  for (let k = 0; k < L.length; k++)
    if (TS.test(L[k].replace(/\r$/, ''))) { L[k] = '; TIMESTAMP_NORMALIZED'; ts++; }
  const np = tmp + '/bi_' + i + '.norm';
  fs.writeFileSync(np, L.join('\n'), 'latin1');
  const sha = cp.execSync('sha256sum ' + np, { encoding: 'latin1' }).split(' ')[0].trim();
  const id = (raw.match(/printing object cube id:(\d+)/) || [, '?'])[1];
  res.push({ sha, bytes: raw.length, ts, id });
  console.log('run ' + (i + 1) + ': raw_bytes=' + raw.length + '  objid=' + id + '  timestamp_lines=' + ts + '  normalised_sha256=' + sha);
}

const allSame = res.every(r => r.sha === res[0].sha);
console.log('');
console.log('self-determinism across ' + N + ' separate processes : ' + (allSame ? 'IDENTICAL' : 'DIFFER'));
console.log('recorded pristine-base normalised sha256            : ' + PRISTINE);
console.log('MODIFIED BUILD vs PRISTINE BASE                     : ' + (res[0].sha === PRISTINE ? 'BYTE-IDENTICAL' : 'DIFFERS'));
console.log('object id identical across runs                     : ' + (res.every(r => r.id === res[0].id) ? 'yes (' + res[0].id + ')' : 'no'));
