// Cross-tree byte-identity proof, measured.
// 1. Verify the preset + test sources are identical across the two trees, so
//    the two exes are running the same inputs.
// 2. Normalize only the exporter's own generated-by/timestamp header line.
// 3. sha256 the normalized bodies and compare base-vs-base, mod-vs-mod,
//    base-vs-mod. Report the fan-line count inside the compared bytes.
const fs = require('fs');
const cp = require('child_process');
const crypto = require('crypto');

const ROOT = '/mnt/c/Users/3ricj/.openvibely/repos/288e09695603e28b9fc187875ade9fdf';
const T = '/mnt/c/Users/3ricj/.openvibely/repos/b286adc9ffdb76b2fe4314806b97ad0a/.worktrees/task_d71213a54c246e952b54f607dae12df4/tmp/byt';

// --- 1. input parity -------------------------------------------------------
console.log('=== input parity between the two trees ===');
for (const rel of ['tests/libslic3r/test_fiber_export_identity.cpp',
                   'tests/fibreseeker/presets/fs3_t1_plastic_machine.json',
                   'tests/fibreseeker/presets/fs3_t1_plastic_process.json',
                   'tests/fibreseeker/presets/fs3_t1_plastic_filament.json',
                   'tests/fibreseeker/presets/fs3_t1_fiber_machine.json']) {
    const a = crypto.createHash('sha256').update(fs.readFileSync(ROOT + '/' + rel)).digest('hex');
    let b = 'MISSING';
    try { b = crypto.createHash('sha256').update(fs.readFileSync(ROOT + '/ctrl1220/' + rel)).digest('hex'); } catch (e) {}
    console.log((a === b ? '  SAME  ' : '  DIFF  ') + rel);
}

// --- 2/3. normalize + compare ---------------------------------------------
function norm(p) {
    const raw = fs.readFileSync(p, 'latin1');
    const lines = raw.split('\n');
    let dropped = 0;
    const out = [];
    for (const l of lines) {
        if (/^;\s*generated by/i.test(l) || /;\s*generated with/i.test(l) ||
            /^;\s*timestamp/i.test(l) || /at \d{1,2}:\d\d/.test(l) && /generated/i.test(l)) {
            dropped++; continue;
        }
        out.push(l);
    }
    const body = out.join('\n');
    const fans = (body.match(/^M106/gm) || []).length;
    return { bytes: Buffer.byteLength(body, 'latin1'), dropped,
             sha: crypto.createHash('sha256').update(body, 'latin1').digest('hex'), fans };
}

const names = ['base1', 'base2', 'mod1', 'mod2'];
const R = {};
console.log('\n=== normalized exports (timestamp line removed) ===');
for (const n of names) {
    const p = T + '/' + n + '.gcode';
    if (!fs.existsSync(p)) { console.log('  MISSING ' + n); process.exit(1); }
    R[n] = norm(p);
    console.log('  ' + n.padEnd(6) + ' bytes=' + String(R[n].bytes).padEnd(8) +
                ' normlines=' + R[n].dropped + '  fanlines=' + String(R[n].fans).padEnd(4) +
                ' sha256=' + R[n].sha);
}

function cmp(a, b, label) {
    const ok = R[a].sha === R[b].sha && R[a].bytes === R[b].bytes;
    console.log('\n' + label + ' : ' + (ok ? 'BYTE-IDENTICAL' : 'DIFFER'));
    if (!ok) {
        const x = fs.readFileSync(T + '/' + a + '.gcode', 'latin1').split('\n');
        const y = fs.readFileSync(T + '/' + b + '.gcode', 'latin1').split('\n');
        let d = 0;
        for (let i = 0; i < Math.max(x.length, y.length) && d < 6; i++)
            if (x[i] !== y[i]) { console.log('   L' + (i + 1) + '\n     - ' + (x[i] || '').slice(0, 90) + '\n     + ' + (y[i] || '').slice(0, 90)); d++; }
    }
    return ok;
}

const selfb = cmp('base1', 'base2', 'pristine run1 vs run2 (self-determinism)');
const selfm = cmp('mod1', 'mod2', 'modified  run1 vs run2 (self-determinism)');
const cross = cmp('base1', 'mod1', 'PRISTINE BASE vs MODIFIED');
const cross2 = cmp('base2', 'mod2', 'PRISTINE BASE vs MODIFIED (second pair)');
console.log('\nfan lines inside compared bytes: base=' + R.base1.fans + ' mod=' + R.mod1.fans +
            (R.base1.fans === R.mod1.fans ? '  EQUAL' : '  MISMATCH'));
console.log('VERDICT: ' + (selfb && selfm && cross && cross2 ? 'NON-CF OUTPUT BYTE-IDENTICAL' : 'NOT IDENTICAL'));
