// Normalise the single non-deterministic line the exporter writes (the
// generation timestamp) and byte-compare the pristine-base export against the
// modified export. Prints a verdict per pair plus sha256 of each normalised file.
const fs = require('fs');
const cp = require('child_process');

const FILES = ['/tmp/base1.gcode', '/tmp/base2.gcode', '/tmp/mod1.gcode', '/tmp/mod2.gcode'];
const TS = /^; generated by .* on .* at .*$/;

function norm(p) {
  const raw = fs.readFileSync(p, 'latin1');
  const lines = raw.split('\n');
  let hits = 0;
  for (let i = 0; i < lines.length; i++)
    if (TS.test(lines[i].replace(/\r$/, ''))) { lines[i] = '; TIMESTAMP_NORMALIZED'; hits++; }
  return { text: lines.join('\n'), ts_lines: hits, bytes: raw.length };
}

const out = {};
for (const f of FILES) {
  const n = norm(f);
  const np = f.replace(/\.gcode$/, '.norm');
  fs.writeFileSync(np, n.text, 'latin1');
  const sha = cp.execSync('sha256sum ' + np, { encoding: 'latin1' }).split(' ')[0].trim();
  out[f] = { sha, bytes: n.bytes, ts_lines: n.ts_lines };
  console.log(f + '  raw_bytes=' + n.bytes + '  timestamp_lines=' + n.ts_lines + '  sha256=' + sha);
}

function cmp(a, b, label) {
  const same = out[a].sha === out[b].sha;
  console.log(label + ': ' + (same ? 'BYTE-IDENTICAL' : 'DIFFER'));
  if (!same) {
    const r = cp.execSync('cmp -l ' + a.replace(/\.gcode$/, '.norm') + ' ' + b.replace(/\.gcode$/, '.norm') + ' || true', { encoding: 'latin1', maxBuffer: 1 << 26 });
    const n = r.split('\n').filter(x => x.trim()).length;
    console.log('  differing bytes: ' + n);
  }
}

cmp('/tmp/base1.gcode', '/tmp/base2.gcode', 'pristine run1 vs pristine run2 (self-determinism)');
cmp('/tmp/mod1.gcode', '/tmp/mod2.gcode', 'modified run1 vs modified run2 (self-determinism)');
cmp('/tmp/base1.gcode', '/tmp/mod1.gcode', 'PRISTINE BASE vs MODIFIED  (the byte-identity claim)');
cmp('/tmp/base2.gcode', '/tmp/mod2.gcode', 'PRISTINE BASE vs MODIFIED  (second run)');
